name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    container: rcywongaa/remy_test:base

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: build
      working-directory: dev_ws
      run: source /opt/ros/foxy/setup.bash && colcon build

    - name: test
      working-directory: dev_ws
      run: source /opt/ros/melodic/setup.bash && colcon test robot_controller # Only test robot_controller for now
