name: incremental_build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    container: rcywongaa/remy_test:moveit

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: ignore_moveit
      working-directory: dev_ws
      run: touch moveit2/COLCON_IGNORE

    - name: build
      working-directory: dev_ws
      run: source /opt/ros/foxy/setup.bash && colcon build

    - name: test
      working-directory: dev_ws
      run: source /opt/ros/foxy/setup.bash && colcon test --packages-up-to robot_controller # Only test robot_controller for now
